---
title: "Analysis of Longevity"
author: "Ryan Abdella"
date: "January 15, 2015"
output:
  html_document:
    css: ~/Github/Food-Optimization/Scripts/foghorn_edited.css
---


```{r Setup, warning = FALSE, message = FALSE, echo = FALSE}

options(stringsAsFactors = FALSE)

source("./Scripts/wMT_fxns.R")
source("./Scripts/survival_fxns.R")
source(paste("./Scripts/", experimentName, ".R", sep = ""))

processedDataPath <- paste("./Data/Processed/", experimentName, sep = "")
saveDataLocation <- paste(processedDataPath, "/", experimentName, sep = "")

paste(experimentName)

```

```{r, warning = FALSE, echo = FALSE}

## Pull in all the files associated with the current experiment  ##
## and create a data frame containing all the raw data.          ##
## Regroup data frame so that it's ordered by strain, replicate, ##
## and day. Add in strain information.                           ##

experimentFile <- dir(path = paste("./Data/Raw/", experimentName, sep = ""), 
             pattern = ".txt", 
             full.names = TRUE)

## Stores the attributes for each experiment. ##

report.df <- processMicrotrackerReport(experimentFile)
binSize = report.df$binSize[1]
numGroups = report.df$numGroups[1]
numBins = report.df$numBins[1]
time = report.df$time[1]

## Now we need to generate a single data frame containing the data from all the ##
## files for the experiment. We also filter the data so that each day has the   ##
## same length of data collection.                                              ##

raw.df <- generateDataFrameFromFile(report.df)

save(raw.df, file = paste(processedDataPath, "/", experimentName, "_Raw.Rda", sep = ""), ascii = TRUE)

## Let's reorganize the data frame so that all the data for a given well is ##
## consecutive and add in strain information which is pulled from the       ##
## experiment configuration file.                                           ##

ordered.df <- raw.df[order(raw.df$col, raw.df$row, raw.df$time), ]
ordered.df$strain <- rep(strains, each = numBins * length(conc))
ordered.df$conc <- rep(rep(conc, each = numBins), 12)

save(ordered.df, file = paste(processedDataPath, "/", experimentName, "_Processed.Rda", sep = ""), ascii = TRUE)

```

## Raw Activity ##

```{r Raw, warning = FALSE, message = FALSE, echo = FALSE, fig.path = paste(processedDataPath, "/", experimentName, "_", sep = ""), fig.width = 15, fig.height = 12}

ggplot(ordered.df) + aes(x = time, y = activity) + geom_point() + facet_grid(row ~ col) +
  labs(x = "Time (minutes)", y = "Raw Activity") + presentation

```

## Cleaned Data ##

```{r, warning = FALSE, message = FALSE, echo = FALSE}

## Remove both columns and individual wells that were contaminated. ##
## This information is specified in the experiment configuration    ##
## file. Need to add the ability to remove only after a certain     ##
## day.                                                             ##

cleaned.df <- ordered.df
cleaned.df$activity[(ordered.df$col %in% colRemove)] <- NA
cleaned.df$activity[(ordered.df$row %in% rowRemove)] <- NA
for(i in 1:nrow(wellRemove)) {
  cleaned.df$activity[cleaned.df$row == wellRemove$row[i] & cleaned.df$col == wellRemove$col[i]] <- NA
}

save(cleaned.df, file = paste(processedDataPath, "/", experimentName, "_Cleaned.Rda", sep = ""), ascii = TRUE)

```

```{r Cleaned, warning = FALSE, message = FALSE, echo = FALSE, fig.path = paste(processedDataPath, "/", experimentName, "_", sep = ""), fig.width = 15, fig.height = 12}

ggplot(cleaned.df) + aes(x = time, y = activity) + geom_line() + facet_grid(row ~ col) +
  labs(x= "Time (minutes)", y = "Raw Activity") + presentation

```

## Well Normalized Data ##

```{r, warning = FALSE, message = FALSE, echo = FALSE}

## Normalize total activity data by the maximum activity of each well. ##
## NEED TO ADD NORMALIZING BY THE NUMBER OF WORMS SORTED. This is also ##
## the same as normalizing the mean values.                            ##

well.df <- cleaned.df %>%
  group_by(col) %>%
  mutate(norm.act = 100 * activity / max(activity, na.rm = TRUE))

well.df <- ungroup(well.df)

save(well.df, file = paste(processedDataPath, "/", experimentName, "_Well.Rda", sep = ""), ascii = TRUE)

```

```{r Well_Normalized, warning = FALSE, message = FALSE, echo = FALSE, fig.path = paste(processedDataPath, "/", experimentName, "_", sep = ""), fig.width = 15, fig.height = 12}

ggplot(well.df) + aes(x = time, y = norm.act) + ylim(0, 100) + geom_line() + facet_grid(row ~ col) +
  labs(x = "Time (minutes)", y = "Normalized Activity") + presentation

```

## Well Variation in Drug Concentration ##

```{r Well_Dose_Response, warning = FALSE, message = FALSE, echo = FALSE, fig.path = paste(processedDataPath, "/", experimentName, "_", sep = ""), fig.width = 15, fig.height = 12}

ggplot(well.df[well.df$time == time, ]) + aes(x = conc, y = activity, color = factor(col)) + geom_line() +
  labs(x = "Concentration of Drug (µM)", y = "Activity") + presentation

ggplot(well.df[well.df$time == time, ]) + aes(x = conc, y = activity) + geom_line() +
  labs(x = "Concentration of Drug (µM)", y = "Activity") + presentation + facet_wrap( ~ col)

```

```{r, warning = FALSE, message = FALSE, echo = FALSE}

## Let's look at the mean and standard deviation of the ##
## data per strain.                                     ##
if (length(strains) != length(unique(strains))) {
  strain.df <- well.df %>%
    group_by(strain, conc, time) %>%
    summarise(mean.activity = mean(activity, na.rm = TRUE), 
              sd.activity = sd(activity, na.rm = TRUE), 
              median.activity = median(activity, na.rm = TRUE), 
              total.activity = sum(activity, na.rm = TRUE))

  strain.df <- ungroup(strain.df)

  for (i in 1:nrow(strain.df)) {
    if (strain.df$total.activity[i] == 0) strain.df$total.activity[i] <- NA
    if (!is.finite(strain.df$mean.activity[i])) strain.df$mean.activity[i] <- NA
    if (!is.finite(strain.df$sd.activity[i])) strain.df$sd.activity[i] <- NA
  }
} else print("No strain replicates to display.")

```

## Strain Mean Data ##

```{r Strain_Mean, warning = FALSE, message = FALSE, echo = FALSE, fig.path = paste(processedDataPath, "/", experimentName, "_", sep = ""), fig.width = 15, fig.height = 12}

if (length(strains) != length(unique(strains))) {
  ggplot(strain.df) + geom_line(aes(x = time, y = mean.activity)) + 
    geom_errorbar(aes(x = time, ymin = mean.activity - sd.activity, ymax = mean.activity + sd.activity)) + 
    facet_grid(conc ~ strain) + labs(x = "Time (minutes)", y = "Mean Activity") + presentation
}

```

## Strain Median Data ##

```{r Strain_Median, warning = FALSE, message = FALSE, echo = FALSE, fig.path = paste(processedDataPath, "/", experimentName, "_", sep = ""), fig.width = 15, fig.height = 12}

if (length(strains) != length(unique(strains))) {
  ggplot(strain.df) + aes(x = time, y = median.activity) + geom_line() + facet_grid(conc ~ strain) +
    labs(x = "Time (minutes)", y = "Median Activity") + presentation
}

```

## Strain Total Data ##

```{r Strain_Total, warning = FALSE, message = FALSE, echo = FALSE, fig.path = paste(processedDataPath, "/", experimentName, "_", sep = ""), fig.width = 15, fig.height = 12}

if (length(strains) != length(unique(strains))) {
  ggplot(strain.df) + aes(x = time, y = total.activity) + geom_line() + facet_grid(conc ~ strain) +
    labs(x = "Time (minutes)", y = "Total Activity") + presentation
}

```

## Strain Normalized Data ##

```{r, warning = FALSE, message = FALSE, echo = FALSE}

if (length(strains) != length(unique(strains))) {
  strain.df <- strain.df %>%
    group_by(strain) %>%
    mutate(norm.act = 100 * total.activity / max(total.activity, na.rm = TRUE))

  strain.df <- ungroup(strain.df)
}

```

```{r Strain_Normalized, warning = FALSE, message = FALSE, echo = FALSE, fig.path = paste(processedDataPath, "/", experimentName, "_", sep = ""), fig.width = 15, fig.height = 12}

if (length(strains) != length(unique(strains))) {
  ggplot(strain.df) + aes(x = time, y = norm.act) + ylim(0, 100) + geom_line() + facet_grid(conc ~ strain) + 
    labs(x = "Time (minutes)", y = "Normalized Activity") + presentation
}

```

## Strain Variation in Drug Concentration ##

```{r Strain_Dose_Response, warning = FALSE, message = FALSE, echo = FALSE, fig.path = paste(processedDataPath, "/", experimentName, "_", sep = ""), fig.width = 15, fig.height = 12}

if (length(strains) != length(unique(strains))) {
  ggplot(strain.df[strain.df$time == time, ]) + aes(x = conc, y = mean.activity, color = strain) + geom_line() +
    labs(x = "Concentration of levamisole (µM)", y = "Mean Activity") + presentation
}

```